{% set version = "2022.3.0" %}

package:
  name: geocat-datafiles
  version: {{ version }}

source:
  url: https://github.com/NCAR/geocat-datafiles/archive/v{{ version }}.tar.gz # For building from a specific tag's tarball
  # sha256: 5213495766a4f443edb32170a8fc3fce317e82436910bc75df6e5b2cd24fa01e
  # git_tag: v{{ version }}   # For building from a specific tag
  # git_rev: march # For building from main branch for debugging purposes
  # git_url: https://github.com/NCAR/geocat-f2py.git

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py<38 or win]

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - pip                                 # [build_platform != target_platform]
    - setuptools                          # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pooch                               # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - pooch
  run:
    - python
    - pooch

test:
  imports:
    - geocat.datafiles

about:
  home: https://geocat.ucar.edu/
  summary: 'GeoCAT-datafiles is a Python module that allows users to download sample datasets for use with GeoCAT projects.'

extra:
  recipe-maintainers:
    - pilotchute
      - erogluorhan
      - anissa111
      - michaelavs
