name: Update Registry

on:
  push:
    branches:
      - main
    
jobs:
  update_registry:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        ref: 'main'
  
    - name: Install dependencies
      run: |
        python -m pip install pip --upgrade
        python -m pip install pooch
          
    - name: Re-Create Registry
      shell: bash
      run: python create_registry.py

    - name: Commit and push changes
      run: |
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '<${{ github.actor }}@users.noreply.github.com>'
        git remote set-url origin https://x-access-token:${{ secrets.SECRET_TOKEN }}
        git add registry.txt
        git commit --allow-empty -m "Update Registry.txt"
        git push -u origin HEAD